export const SRI_LANKA_CITIES = [
  'Agalawatta','Agunukolapelassa','Ahangama','Ahungalla','Akkareipathuwa',
  'Akmeemana','Akuressa','Alawwa','Alutgama','Ambalangoda','Ambalantota',
  'Ambepussa','Ampara','Anamaduwa','Anuradhapura','Aralaganwila','Arugam Bay',
  'Athurugiriya','Attanagalla','Avissawella','Badulla','Balapitiya','Balangoda',
  'Bandaragama','Bangadeniya','Battaramulla','Batticaloa','Bemmulla','Beruwala',
  'Bogawantalawa','Boralesgamuwa','Buthpitiya','Chavakachcheri','Chilaw',
  'Colombo 01','Colombo 02','Colombo 03','Colombo 04','Colombo 05',
  'Colombo 06','Colombo 07','Colombo 08','Colombo 09','Colombo 10',
  'Colombo 11','Colombo 12','Colombo 13','Colombo 14','Colombo 15',
  'Dankotuwa','Dedigama','Dehiattakandiya','Dehiwala','Deraniyagala',
  'Divulapitiya','Dodangoda','Dondra','Eheliyagoda','Elpitiya','Embilipitiya',
  'Eppawala','Galgamuwa','Galle','Gampaha','Gampola','Ganemulla','Ginigathhena',
  'Giriulla','Godakawela','Gonapinuwala','Hambantota','Haputale','Hatton',
  'Hettipola','Hikkaduwa','Homagama','Horana','Ibbagamuwa','Ingiriya',
  'Ja-Ela','Jaffna','Kalmunai','Kalutara','Kamburupitiya','Kandy','Katana',
  'Kataragama','Katugastota','Kelaniya','Kegalle','Kilinochchi','Kirindiwela',
  'Kiriella','Kohuwala','Kosgama','Kosgoda','Kotadeniyawa','Kuliyapitiya',
  'Kurunegala','Laggala','Maharagama','Mahiyanganaya','Marawila','Matale',
  'Matara','Maviddapuram','Millaniya','Minuwangoda','Mirigama','Moneragala',
  'Moratuwa','Mount Lavinia','Mullaitivu','Mundalama','Nawalapitiya','Negombo',
  'Nikaweratiya','Nittambuwa','Nuwara Eliya','Pasyala','Peliyagoda',
  'Peradeniya','Piliyandala','Polgahawela','Polonnaruwa','Pugoda','Puttalam',
  'Ragama','Rajagiriya','Ratmalana','Ratnapura','Seeduwa','Siyambalanduwa',
  'Sri Jayawardenapura Kotte','Tangalle','Thalawathugoda','Thambuttegama',
  'Tissamaharama','Trincomalee','Udugama','Vavuniya','Wattala','Weligama',
  'Welimada','Wennappuwa','Yatiyanthota',
].sort();

export const LOCATION_TYPES = [
  'House',
  'Apartment',
  'Office',
  'Hospital',
  'School',
  'Funeral Home',
  'Wedding Reception',
  'Hotel',
  'Other',
];

